baseurl = "http://murgash.veloclubmammut.com/"
title = "Купа Мургаш 2017"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Купа Мургаш 2017"
  description = '<!--[-->Неделя, 17 Септември 2017<!--]--><br /><!--[-->С подкрепата на  <a href="https://maxcombike.bg/">Максбайк</a><!--]--><br />'
  logo = "fa-bicycle"
  copyright = "Veloclub Mammut 2017"

#[[params.social]]
#  medium = "twitter"
#  icon = "twitter"
#  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/murgash.xcm/"

#[[params.social]]
#  medium = "instagram"
#  icon = "instagram"
#  link = "#"

#[[params.social]]
#  medium = "github"
#  icon = "github"
#  link = "#"

[languages]
[languages.bg]
languageName = "Български"
weight = 1
title = "Купа Мургаш 2017"
description = '<!--[-->Неделя, 17 Септември 2017.  <!--]--><br /><!--[-->С подкрепата на  <a href="http://maxcombike.com/">Максбайк</a>, <a href="https://pavebikeshop.com/">PaVé Bike Shop</a>, <a href="http://highfive-bg.com/">High5</a>, <a href="http://www.avitel-bg.com/">Авител</a>, <a href="http://www.racetimingbg.com/">Race Timing BG</a><!--]--><br />'
