baseurl = "http://murgash.veloclubmammut.com/"
title = "Купа Мургаш 2018"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "bg"
enableRobotsTXT = true
disableRSS = true

[params]
    logo = "fa-bicycle"
    copyright = "Велоклуб Мамут 2018"
    title = "Купа Мургаш 2018"
    description = '<!--[-->Неделя, 23 Септември 2018.  <!--]--><br /><!--[-->С подкрепата на  <a href="http://maxcombike.com/">Максбайк</a>, <a href="https://pavebikeshop.com/">PaVé Bike Shop</a>, <a href="http://highfive-bg.com/">High5</a>, <a href="http://www.avitel-bg.com/">Авител</a>, <a href="http://www.racetimingbg.com/">Race Timing BG</a><!--]--><br />'

#[[params.social]]
#  medium = "twitter"
#  icon = "twitter"
#  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/murgash.xcm/"

#[[params.social]]
#  medium = "instagram"
#  icon = "instagram"
#  link = "#"

#[[params.social]]
#  medium = "github"
#  icon = "github"
#  link = "#"

[languages]
  [languages.bg]
    languageName = "Български"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
    title = "Murgash Cup 2018"
    description = '<!--[-->Sunday, 23 September 2018.  <!--]--><br /><!--[-->Our sponsors:  <a href="http://maxcombike.com/">Maxbike</a>, <a href="https://pavebikeshop.com/">PaVé Bike Shop</a>, <a href="http://highfive-bg.com/">High5</a>, <a href="http://www.avitel-bg.com/">Avitel</a>, <a href="http://www.racetimingbg.com/">Race Timing BG</a><!--]--><br />'
    logo = "fa-bicycle"
    copyright = "Veloclub Mammut 2018"


