baseurl = "http://murgash.veloclubmammut.com/"
title = "Купа Мургаш 2018"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "bg"
enableRobotsTXT = true
disableRSS = true

[params]
    logo = "fa-bicycle"
    copyright = "Велоклуб Мамут 2018"
    title = "Купа Мургаш 2018"
    description = '
        <!--[--><b>Неделя, 23 Септември 2018</b>.<br /><!--]-->
<b><a href="https://ads.mercedes-benz.bg/x-class-test-drive">Генерален спонсор: Mercedes-Benz Silver Star</a></b><br />
        <!--[--><span style="font-size: small">С подкрепата на:</span> <br />
            <a target="_blank" href="https://pavebikeshop.com/">PaVé Bike Shop</a>,
            <a target="_blank" href="https://www.race-series.com/">Race Series</a>,
            <a target="_blank" href="https://www.pulse-cycles.com/en/">Pulse Cycles</a>,
            <a target="_blank" href="http://olimpbg.com/">Олимп</a>,
            <a target="_blank" href="https://basecamp-shop.com/">Basecamp</a>,
            <br />
            <a target="_blank" href="https://bike.shimano.com/en-US/home.html">Shimano</a>,
            <a target="_blank" href="https://www.isostar.com/">Isostar</a>,
            <a target="_blank" href="http://www.hotelsunrisebansko.com/">Хотел Sunrise Банско</a>,
            <a target="_blank" href="http://effect.bg/">Ефект</a>,
            <a target="_blank" href="https://www.epay.bg/v3main/sale/user/view?saleid=7793633475">EPay</a>,
            <a target="_blank" href="https://www.easypay.bg/site">EasyPay</a>
            <!--]-->

        <!--[--><br />
            <span style="font-size: small">Медийни партньори:</span> <br />
            <a target="_blank" href="http://www.racetimingbg.com/">Race Timing BG</a>,
            <a target="_blank" href="http://www.mtb-bg.com/">MTB-BG</a>,
            <a target="_blank" href="http://www.velocafe.bg/">VeloCafe</a>
        <!--]-->'

#[[params.social]]
#  medium = "twitter"
#  icon = "twitter"
#  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/murgash.xcm/"

#[[params.social]]
#  medium = "instagram"
#  icon = "instagram"
#  link = "#"

#[[params.social]]
#  medium = "github"
#  icon = "github"
#  link = "#"

[languages]
  [languages.bg]
    languageName = "Български"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
    title = "Murgash Cup 2018"
    description = '
        <!--[--><p>Sunday, 23 September 2018.</p><!--]-->
        <!--[--><span style="font-size: small">Our sponsors:</span> <br />
            <a target="_blank" href="https://pavebikeshop.com/">PaVé Bike Shop</a>,
            <a target="_blank" href="https://www.race-series.com/">Race Series</a>,
            <a target="_blank" href="https://www.pulse-cycles.com/en/">Pulse Cycles</a>,
            <a target="_blank" href="http://olimpbg.com/">Olimp</a>,
            <a target="_blank" href="https://basecamp-shop.com/">Basecamp</a>,
            <br />
            <a target="_blank" href="https://bike.shimano.com/en-US/home.html">Shimano</a>,
            <a target="_blank" href="https://www.isostar.com/">Isostar</a>,
            <a target="_blank" href="http://www.hotelsunrisebansko.com/">Hotel Sunrise Bansko</a>,
            <a target="_blank" href="http://effect.bg/">Effect</a>,
            <a target="_blank" href="https://www.epay.bg/v3main/sale/user/view?saleid=7793633475">EPay</a>,
            <a target="_blank" href="https://www.easypay.bg/site">EasyPay</a>
            <!--]-->

        <!--[--><br />
            <span style="font-size: small">Media partners:</span> <br />
            <a target="_blank" href="http://www.racetimingbg.com/">Race Timing BG</a>,
            <a target="_blank" href="http://www.mtb-bg.com/">MTB-BG</a>,
            <a target="_blank" href="http://www.velocafe.bg/">VeloCafe</a>
        <!--]-->'

    logo = "fa-bicycle"
    copyright = "Veloclub Mammut 2018"


